export const cards = {
  fun: [
    "What would you do if you were on a deserted island? ",
    "Have you ever been in a bar fight?",
    "What's your guilty pleasure song?",
    "What is your favorite activity? ",
    "What's your favorite type of weather?",
    "What's your full name?",
    "You're given $1 million to spend on anything you want—what are you buying? ",
    "Who is the funniest person in your group of friends?",
    "Have you ever participated in ding-dong-ditch? ",
    "What's a mistake you've made that you still feel guilty about? ",
    "Do you carry cash?",
    "Who in your group is the quickest thinker?",
    "What's something you've Googled that you aren't proud to admit? ",
    "What movie have you watched the most? ",
    "Do you enjoy watching kid's shows or cartoons?",
    "Who in the group has the most attractive parents? ",
    "Be honest, do you pee in the shower?",
    "What's your favorite TV show? ",
    "Have you ever talked to a fortune teller? And did you believe them?",
    "Have you ever run out of toilet paper?",
    "Describe your most embarrassing moment.",
    "How much money do you have on you right now?",
    "Do you buy drinks for strangers to try and get to know them?",
    "Are you more of a waffle or pancake person? ",
    "Cats or Dogs?",
    "What's your dream job?",
  ],
  dare: [
    "If your birhtday is on April 12, tell your partner that you love them.",
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "If your name starts K, kiss your boyfriend/girlfriend.",
    "If your last name starts with S, send a dirty picture to *",
    "Let the rest of the group DM someone from your Instagram account",
    "Do 100 squats",
    "Jump 10 times",
    "Keep three ice cubes in your mouth until they melt",
    "Yell out the first word that comes to your mind",
    "Keep your eyes closed until it's your go again",
    "Pretend to be * for 10 minutes",
    "Whisper a secret to *.",
    "Say two honest things about everyone else in the group",
    "Show your favourite picture of yourself",
    "Show the most beautiful picture you have on your phone.",
    "Sing your favorite song.",
    "Seductively eat a banana",
  ],
  spicy: [
    "Have you ever given someone a lap dance?",
    "What’s the dirtiest text you’ve ever received?",
    "Would you hook up with your high school crush?",
    "What’s your biggest turn-on?",
    "Have you ever had a one-night stand?",
    "What’s your favorite sex position?",
    "Have you ever touched someonelse's genitals?",
    "Have you ever fondled someonelse's private part?",
    "What’s your biggest turn-off?",
    "How many sex toys do you own?",
    "Have you ever tried to hook up with your best friend’s crush?",
    "Would you ever hook up with someone who is in a relationship?",
    "Do you prefer to get drunk before sleeping with someone? ",
    "What's your craziest one-night stand story? ",
    "Have you ever accidentally sent a dirty text to the wrong recipient?",
    "Have you ever recorded a dirty tape?",
    "What's the most embarrassing experience you've had while in bed? ",
    "Has a teacher ever flirted with you? Or, have you ever flirted with a teacher? ",
    "Who in this room do you find the hottest?",
    "What's your body count?",
    "Do you find * sexy?",
    "What's your favorite position in bed? ",
    "Have you ever sexted someone you just met? ",
    "Have you ever had a sexual video call will someone?",
    "Have you ever sexted someone you just met? ",
    "What color is your underwear",
    "Does * turn you on?",
    "Name two person you would want to have threesome with.",
  ],
  personal: [
    "What's one thing you've always wanted to say to * but haven't?",
    "Describe a moment when you felt let down by *.",
    "What's your biggest insecurity in your relationship?",
    "Have you ever considered ending your relationship? When and why?",
    "Is there something you've done with your partner that you regret deeply?",
    "What's the most significant secret you've kept from *?",
    "Have you ever lied to your SO about something important?",
    "What's one thing about * that you find difficult to accept?",
    "Do you have any doubts about your future with your current boyfriend/girlfriend?",
    "Do you judge people based on their appearance? ",
    "What would you do if you were on a deserted island? ",
    "What's your guilty pleasure song? ",
    "What is your favorite activity?",
    "Do you like to stay in or go out?",
    "What's the first thing you want to do when you start to get tipsy",
  ],
};
